### PR TITLE
Added some positioning functionality.  Added default contextmenu stylesheet

### PR DESCRIPTION
**Pull request by jlipford**
The positioning enhancements just give the user finer control over placement. 
The stylesheet ensures that the li element properly fills out the width no matter if the icon is there or not. Also the separator can be better acheived visually using a border than an hr tag.

### CODE REVIEW

**Comment by OpenSourceCodeProjects** [comment]
Hi Josh,

Thank you for you contributions to the context menu.  I am in the process of reviewing the changes.  I hope to merge the pull request today.

Regards,

John DeVight

**Comment by jlipford** [comment]
No problem,

I was using a previous kendo context menu github project (
https://github.com/jlipford/kendoui.ex)  but it broke with the latest
version so I incorporated some of the features into your control.
 Hoepfully they are gobal enough for other users as well.

I like the project idea and plan on contributing!

**Comment by OpenSourceCodeProjects** [comment]
Glad to hear that you plan on contributing!  I look forward to working with you on additions to the repo.  I hope to have guidelines available by this summer for anyone who wants to author their own widgets.  Also, let me know if there are any widgets you would like to see created.  I'll check out the kendoui.ex repo to see if it makes sense to port any of it over to this repo.

I made a few adjustments to your changes to the contextmenu.  I brought back the items configuration setting.  Both items and dataSource will be supported until Kendo UI 2014 Q1 when the items configuration will be deprecated in favor of the dataSource configuration setting.

I added support for the slide effect back in and have made it configurable between slide and fade.  It is configurable with the following:

animation: {
    close: {
        effects: "fade"
    },
    open: {
        effects: "fade"
    }
}

Let me know if my updates have caused any problems.  If it did, I'd like to work together to resolve them.

Thanks again!

John DeVight

**Comment by jlipford** [comment]
John,

No problem and going forward I will try to make any breaking changes
configurable that way it makes it easy for your integrate.   And pardon me
if I check in a lot of small packages as I make adjustments as needed as I
am working on a large web application that will utilize the context menu. I
will do my best to explain each one and isolate into separate commits.

The only widgets on my mind right now are related to windows/dialogs.  I am
looking into your dialogs code and it looks promising!  I love how you
utilized defer to send back a response that mimics forms dialog workflow
and I will have to read up as I am not as familiar with defer as I have not
used it often.  I will probably try to integrate some type of dialog that
allows for iframe/ajax loading but I have no hit that scenario just yet.

**Pull request merged**
